rc: Highlight GDScript
kakoune-editor/kakoune-extra-filetypes pull request #8
Opened 2021-08-06 07:21 UTC by kkga

2021-08-07 03:44 UTC, lenormf requested changes

2021-08-07 03:44 UTC, lenormf commented on rc/gdscript.kak
> +add-highlighter shared/gdscript/code/ regex '\b\d+\.'                         0:value
Is that a valid number in GDScript? E.g. `123.`?

2021-08-07 03:44 UTC, lenormf commented on rc/gdscript.kak
> +add-highlighter shared/gdscript/code/ regex _?[a-zA-Z]\w*\s*(?=\()            0:function
Could the actual function name be captured here, to avoid highlighting trailing whitespace (the `\s*`)?

2021-08-07 03:44 UTC, lenormf commented on rc/gdscript.kak
> +add-highlighter shared/gdscript/code/ regex (?:func\h+)(_?\w+)(?:<[^>]+?>)?\( 1:function
Is `__a` a valid function name? The regex above is more specific, using `[a-zA-Z]` instead of `\w` which includes `_`.

2021-08-07 03:44 UTC, lenormf commented on rc/gdscript.kak
> +add-highlighter shared/gdscript/code/ regex '(?:\+|-|\*|/|%|=|<|>|&|\||\^|~|:=)' 0:operator
We can probably remove the non capturing parenthesis group here.

2021-08-07 03:44 UTC, lenormf commented on rc/gdscript.kak
> +        add-highlighter shared/gdscript/code/ regex '\b($(join "${builtin_classes}" '|'))\b' 0:type
This probably won't match the `@GDScript` and `@GlobalScope` symbols, because they start with a `@` and the regex requires `\b`.

2021-08-07 03:44 UTC, lenormf commented on rc/gdscript.kak
> +add-highlighter shared/gdscript/code/ regex '\$[\w/]*'                        0:module
Is `$` a valid module? The `*` should probably be a `+`.

2021-08-17 07:27 UTC, lenormf commented
The script has been merged as-is upstream.

2021-08-17 07:27 UTC, closed without merging

2021-08-17 08:58 UTC, kkga commented
@lenormf Thank you for the thorough review! I'll address these issues in a separate PR upstream.